name: submodule update
on:
  workflow_dispatch:

  pull_request:
    types: [synchronize]
    branches:
      - no_upload_master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: cidgoh/covidmvp_deployment
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init
          git submodule update --remote
      - name: Commit
        run: |
          git config user.email "despean15@gmail.com"
          git config user.name "despean"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push